avl:
	clang++ --std=c++23 -O3 avl.cpp -o avl && ./avl

hash:
	clang++ --std=c++23 hash.cpp && ./a.out

avldebug:
	clang++ --std=c++23 -g avl.cpp -o debug

hashdebug:
	clang++ --std=c++23 -g hash.cpp -o debug
